### ISSUE TITLE
Integration testing: databases

### ISSUE THREAD

**Issue by isedwards** [opencdms/opencdms-test-data#1]
This epic is focused on allowing testers to create the necessary database test environment in order to run tests with a specific database backend instead of the sqlite defualt used for unit testing.

**Comment by marvelous-benji** [comment]
With the help of the python library [docker](https://pypi.org/project/docker/), we can create and interact programmatically with desired docker containers for tests, so we can always spin up databases containers  programmatically for test. @isedwards what do you think.
